modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tripwired"
version="beta 0.1.0"
displayName="Tripwired"
credits="Created using MCreator"
displayURL="https://mcreator.net"
authors="Sayne, Pheonix"

[[dependencies.tripwired]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




