modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tripwired"
version="1.0.0"
displayName="Tripwired"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Blood, MCreator"

[[dependencies.tripwired]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




